### ISSUE TITLE
Stopped working after upgrading to Home Assistant version .110

### ISSUE THREAD

**Issue by mkanet** [custom-cards/stack-in-card#8]
I just upgraded to Home Assistant version .110 (from version .109).  One of the first things I noticed is my cards that use stack-in-card is broken.

It looks like the issue is more-specifically related to using stack-in-card in combination with vertical-stack'ing cards.  

`

        type: vertical-stack
        cards:
        - cards:
            - entities: null
                entity: sensor.sabnzbd_speed
                max: 100
                min: 0
                severity:
                green: 10
                red: 30
                yellow: 25
                type: gauge
            - entities:
                - entity: sensor.sabnzbd_status
                - entity: sensor.sabnzbd_daily_total
                - entity: sensor.sabnzbd_weekly_total
                - entity: sensor.sabnzbd_monthly_total
                - entity: sensor.sabnzbd_left
                - entity: sensor.sabnzbd_queue
                - entity: sensor.sabnzbd_queue_count
                type: entities
            title: SABnzbd
            type: 'custom:stack-in-card'
        - entities:
            - entity: sensor.asuswrt_download_speed
            - entity: sensor.asuswrt_upload_speed
            title: Asus Router
            type: entities

Is there any kind of work-around to get this working until there's a fix?  My Home Assistant pages heavily rely on stack-in-card +vertical stacking,  I didn't realize how critical this custom card was to my setup!

**UPDATE:**  It looks like this issue only happens when using Chrome web browser.  It doesn't happen when using the Home Assistant Android app.  @RomRider , could you please tell me is this is a bug with Home Assistant or Stack-in-card?  So far, your card is the only card that seems to have trouble with the latest version of Home Assistant.

**Comment by RomRider** [comment]
What do you mean by broken?

**Comment by Knapoc** [comment]
I too have issues in Safari... in Firefox it works without issues. For me the cards go blank or disappear completely when refreshing the window 

Web inspector messages:
```
[Error] Unhandled Promise Rejection: TypeError: t.setConfig is not a function. (In 't.setConfig(e)', 't.setConfig' is undefined)
	(anonymous function) (chunk.3794da5240b9979884e1.js:2140:317637)
	promiseReactionJob
[Error] hui-thermostat-card – Error: Specify an entity from within the climate domain.
Error: Specify an entity from within the climate domain.value — hui-light-card.ts:36s — hui-weather-forecast-card.ts:39value — hui-card-picker.ts:42(anonymous function) — hui-card-picker.ts:42asyncFunctionResume[native code]promiseReactionJobWithoutPromisepromiseReactionJob
	s (chunk.3794da5240b9979884e1.js:2140:317365)
	value (chunk.8cc8e3dda2dd9f37ee72.js:146:46847)
	(anonymous function) (chunk.8cc8e3dda2dd9f37ee72.js:146:47483)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this._hass.states')
	(anonymous function) (button-card.js:1588)
	promiseReactionJob
[Error] hui-alarm-panel-card – Error: Invalid card configuration
Error: Invalid card configuration
	s (chunk.3794da5240b9979884e1.js:2140:317365)
	value (chunk.8cc8e3dda2dd9f37ee72.js:146:46847)
	(anonymous function) (chunk.8cc8e3dda2dd9f37ee72.js:146:47483)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this._hass.states')
	(anonymous function) (button-card.js:1588)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (index.m.js.map, line 0)

**Comment by mkanet** [comment]
> What do you mean by broken?

Please see below.  

**Home Assistant version .109 and older:**
![Correct](https://user-images.githubusercontent.com/811008/82683826-7ed75700-9c06-11ea-9c5c-da7475a7809e.png)

**Home Assistant version .110 (using Chrome Web browser):**
Notice that as the screen draws, the card that utilizes stack-in-card disappears quickly right after it's displayed.  **Please note, cards that utilize Stack-in-card still correctly by themselves.**  However, when using these cards in a regular vertical-stack (or horizontal-stack), the cards that uses stack-in-card disappears: 
![Overview - Home Assistant - Google Chrome 2020-05-22 08-26-46](https://user-images.githubusercontent.com/811008/82683897-9d3d5280-9c06-11ea-9ce7-9380e9bbb046.gif)

**Comment by RomRider** [comment]
I think this is related to a bug in homeassistant which will probably be fixed in 0.110.2 as it has been closed already.
See https://github.com/home-assistant/frontend/issues/5965

**Comment by mkanet** [comment]
Thanks for looking into it.  I'm just curious what stack-in-card users should do that are experiencing this issue?  I'm guessing this same issue existing with the older vertical stack-in-card custom card too.  Is there some kind of workaround until version .110.2 is available?

**Comment by RomRider** [comment]
There's no workaround ATM appart from rolling back to 0.109.x or building the frontend from source yourself as the issue comes from a core card.
Honestly, the fix will be released soon in core, so I would just be patient (it's a matter of hours probably). I understand it can be frustrating but this is open source and we all do our best :blush:

**Comment by mkanet** [comment]
Thanks for letting me know. I didn't realize Home Assistant has smaller, more granular updates.  Honestly, this was my first ever update to Home Assistant; and, though I had to wait for the next major update.   Anyway, thank you for making such a useful custom card, it's actually one of my favorites.  Ill look for the next update when it becomes available.

**Comment by Knapoc** [comment]
still not working for me with the most recent release (caches etc are cleared)

**Comment by conrad66** [comment]
I have the same problem in firefox on home assistant ( venv ) 0.110.2
The card opens for 2 seconds and closes.
![Screenshot_18](https://user-images.githubusercontent.com/5843698/82762525-2f617880-9e0a-11ea-96db-ce66889930f6.png)

**Comment by mkanet** [comment]
The issue wasn't resolved with version .110.2.  It would be great to know definitively which version our cards will start working correctly again.

**Comment by RomRider** [comment]
I'll have a look at the problem

**Comment by RomRider** [comment]
This should now be fixed in 0.1.1, please report back

**Comment by Knapoc** [comment]
Issue is resolved for me. Thank you for the fix.

**Comment by conrad66** [comment]
Issue is resolved for me too.

**Comment by mkanet** [comment]
The issue is resolved for me too.  Thank you!
